#open project or snowfall > .Rprofile 
# Rprofile:
#  a) >slib230514.R #load CRAN packages
#  b) >source(dumptest.R) #custom autogen library 'B'

#three
#A funlist.R : non-execute list of anest functions used [230501a funlist.R]
#B dumptest.R : autogenerated library  [230501 dumptest.r]
#C dodump.R : C(A)->B dodump(funlist)->dumptest [230501 dumpfunlist.R]

