#open project or snowfall > .Rprofile 
# Rprofile:
#  a) >slib230514.R #load CRAN packages
#  b) >source(c-cleanlib.R) #source custom autogen library 'B'

#A a-funlist.R : non-execute list of anest functions used [230501a funlist.R]
#B b-dodump.R : B(A)->C dodump(funlist)->dumptest [230501 dumpfunlist.R]
#C c-cleanlib.R : autogenerated library  [230501 dumptest.r]

#to add/delete from library update a-funlist then run b-dodump
#to update the library copy of code, run b-dodump
#to load the library into globalenv, run c-cleanlib

if(F) {source('c-cleanlib.R')} #already run in local .Rprofile
x1 <- fread('a-funlist.R',header=F)[,V1]
stopifnot(all(x1%in%ls())) #check c contains all functions listed in a

