library(magrittr)
c( 
'colorspace',
'data.table',
'devtools',   
'ggplot2',    
'ggrepel',    
'lubridate',
'magrittr',   
'plotly',  
'scales',
'signal',     
'snowfall',   
'urca',       
'vars',       
'zoo'       
)%>%
  unique(.)%>%
  sort(.)%>%
  sapply(.,library,character.only=T)%>%
  suppressPackageStartupMessages(.)
